// src/lib/components/UnitNumberDisplay.svelte
<script lang="ts">
    import {
        UnitSystem,
        distanceUnit,
        metersPerSecondToUnit,
        metersToUnit,
        velocityUnit,
    } from "$lib/core/units";
    import NumberDisplay from "./NumberDisplay.svelte";

    export let label: string;
    export let parentheses: boolean = false;
    export let plusPositive: boolean = false;
    export let fractionalDigits: number = 2;

    export let value: number;
    export let baseUnit: "distance" | "velocity";
    export let unitSystem: UnitSystem;

    let valueConverted: number;
    let unit: string;

    $: {
        if (baseUnit === "distance") {
            valueConverted = metersToUnit(value, unitSystem);
            unit = distanceUnit(unitSystem);
        } else if (baseUnit === "velocity") {
            valueConverted = metersPerSecondToUnit(value, unitSystem);
            unit = velocityUnit(unitSystem);
        }
    }
</script>

<NumberDisplay
    {label}
    value={valueConverted}
    {unit}
    {fractionalDigits}
    {parentheses}
    {plusPositive}
/>

// editor/src/components/UnitNumberDisplay.tsx
import type { UnitSystem } from "../contexts/UnitContext";
import { getUnitLabel, toDisplay } from "../lib/unitConversions";
import { NumberDisplay } from "./NumberDisplay";

interface Props {
    label: string;
    value: number;
    baseUnit: "distance" | "velocity";
    unitSystem: UnitSystem;
    parentheses?: boolean;
    plusPositive?: boolean;
    fractionalDigits?: number;
}

export function UnitNumberDisplay({
    label,
    value,
    baseUnit,
    unitSystem,
    parentheses,
    plusPositive,
    fractionalDigits = 2,
}: Props) {
    const base = baseUnit === "distance" ? "m" : "m/s";
    const valueConverted = toDisplay(value, base, unitSystem);
    const unit = getUnitLabel(base, unitSystem);

    return (
        <NumberDisplay
            label={label}
            value={valueConverted}
            unit={unit}
            fractionalDigits={fractionalDigits}
            parentheses={parentheses}
            plusPositive={plusPositive}
        />
    );
}
