// src/components/LaunchCalculator.tsx
import { useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { NumberScroll } from "./NumberScroll";
import { NumberDisplay } from "./NumberDisplay";
import { G } from "../lib/core/constants";
import { LabelWithHelp } from "./LabelWithHelp";

interface Props {
    open: boolean;
    onOpenChange: (v: boolean) => void;
}

export function LaunchCalculator({ open, onOpenChange }: Props) {
    const [launchVelocity, setLaunchVelocity] = useState(10);
    const [launchAccel, setLaunchAccel] = useState(1);

    const launchTime = launchVelocity / (launchAccel * G);
    const launchLength = 0.5 * (launchAccel * G) * (launchTime * launchTime);

    return (
        <Dialog.Root open={open} onOpenChange={onOpenChange}>
            <Dialog.Portal>
                <Dialog.Overlay className="fixed inset-0 z-50 bg-black/60" />
                <Dialog.Content className="fixed left-1/2 top-1/2 z-50 w-full max-w-[490px] -translate-x-1/2 -translate-y-1/2 border border-neutral-700 bg-neutral-800 p-5 shadow-lg outline-none text-neutral-200">
                    <Dialog.Title className="flex w-full items-center justify-center text-lg font-semibold text-neutral-100">
                        Launch track calculator
                    </Dialog.Title>
                    <Dialog.Description className="text-sm text-neutral-400 text-center mb-4">
                        Calculates launch time, and launch track length given an acceleration and a desired velocity.
                    </Dialog.Description>
                    <div className="flex flex-col gap-2 py-2">
                        <label className="flex items-center justify-between">
                            <span className="mr-2 text-sm text-neutral-400">
                                <LabelWithHelp label="Velocity" topic="target-velocity" />
                            </span>
                            <NumberScroll
                                value={launchVelocity}
                                onChange={setLaunchVelocity}
                                fractionalDigits={0}
                                min={0.1}
                            />
                        </label>
                        <label className="flex items-center justify-between">
                            <span className="mr-2 text-sm text-neutral-400">
                                <LabelWithHelp label="Launch Acceleration" topic="launch-acceleration" />
                            </span>
                            <NumberScroll
                                value={launchAccel}
                                onChange={setLaunchAccel}
                                min={0.1}
                            />
                        </label>
                        <NumberDisplay unit="m" value={Math.ceil(launchLength)} label="Min Launch Length" />
                        <NumberDisplay unit="s" value={launchTime} label="Min Launch Time" />
                        <Dialog.Close className="button w-min ml-auto mt-2">
                            Close
                        </Dialog.Close>
                    </div>
                </Dialog.Content>
            </Dialog.Portal>
        </Dialog.Root>
    );
}

// src/lib/components/LaunchCalculator.svelte
<script lang="ts">
    import { Dialog } from "bits-ui";
    import NumberScroll from "./NumberScroll.svelte";
    import NumberDisplay from "./NumberDisplay.svelte";
    import { G } from "$lib/core/constants";

    export let open = false;

    let launchVelocity = 10;
    let launchAccel = 1;

    $: launchTime = launchVelocity / (launchAccel * G);
    $: launchLength = 0.5 * (launchAccel * G) * (launchTime * launchTime);
</script>

<Dialog.Root bind:open>
    <Dialog.Portal>
        <Dialog.Overlay
            transitionConfig={{ duration: 150 }}
            class="fixed inset-0 z-50 bg-black/80"
        />
        <Dialog.Content
            class="fixed left-[50%] top-[50%] z-50 w-full max-w-[94%] translate-x-[-50%] translate-y-[-50%] border bg-background p-5 shadow-popover outline-none sm:max-w-[490px] md:w-full"
        >
            <Dialog.Title
                class="flex w-full items-center justify-center text-lg font-semibold tracking-tight"
                >Launch track calculator</Dialog.Title
            >
            <Dialog.Description class="text-sm text-foreground-alt">
                Calculates launch time, and launch track length given an
                acceleration and a desired velocity.
            </Dialog.Description>
            <div class="flex flex-col py-4">
                <label
                    ><span class="mr-2">Velocity: </span>
                    <div class="float-right">
                        <NumberScroll
                            bind:value={launchVelocity}
                            fractionalDigits={0}
                            min={0.1}
                        />
                    </div>
                </label>
                <label
                    ><span class="mr-2">Acceleration: </span>
                    <div class="float-right">
                        <NumberScroll bind:value={launchAccel} min={0.1} />
                    </div>
                </label>

                <NumberDisplay
                    unit="m"
                    value={Math.ceil(launchLength)}
                    label="Min Launch Length"
                />
                <NumberDisplay
                    unit="s"
                    value={launchTime}
                    label="Min Launch Time"
                />

                <Dialog.Close class="button w-min ml-auto">
                    <div>Close</div>
                </Dialog.Close>
            </div>
        </Dialog.Content>
    </Dialog.Portal>
</Dialog.Root>
